### ISSUE TITLE
[documentation] Typo in README.md

### ISSUE THREAD

**Issue by Krokette** [AuroreVanHoorebeke/AuroreVanHoorebeke.github.io#1]
@AuroreVanHoorebeke 
There's a typo in the end of the [README.md](https://github.com/AuroreVanHoorebeke/AuroreVanHoorebeke.github.io/blob/master/README.md) 

> It's still the beginning, and I'm **opened** to all **suggetions**!

should be 

> It's still the beginning, and I'm **open** to all **suggestions**!

**Comment by AuroreVanHoorebeke** [comment]
Solved!
